/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
  aws_project_region: "ap-southeast-1",
  // aws_cognito_identity_pool_id:
  //   "ap-southeast-1:c9d38a68-2282-46fd-a551-7963337fc085",
  aws_cognito_region: "ap-southeast-1",
  aws_user_pools_id: "ap-southeast-1_st0p20eSz",
  aws_user_pools_web_client_id: "55ae5bvha428nr80ccre3dl4au",
  secure: true,
  oauth: {
    domain: "dube.auth.ap-southeast-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "profile",
      "openid",
      "aws.cognito.signin.user.admin",
    ],

    redirectSignIn: process.env.REACT_APP_REDIRECT_URL,
    redirectSignOut: process.env.REACT_APP_REDIRECT_URL,
    responseType: "token",
  },

  aws_cognito_social_providers: ["GOOGLE"],
};

export const config = {
  REGION: "ap-southeast-1",
  USER_POOL_ID: "ap-southeast-1_st0p20eSz",
  USER_POOL_APP_CLIENT_ID: "dubeuserpoolreadonlyclient7B2CD6CF-luGhtYvx35oI",
};

export default awsConfig;
