/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { Auth } from 'aws-amplify';

const awsConfig = {
  aws_project_region: process.env.REACT_APP_AWS_PROJECT_REGION,

  aws_cognito_region: process.env.REACT_APP_AWS_PROJECT_REGION,
  aws_user_pools_id: process.env.REACT_APP_AWS_USER_POOLS_ID,
  aws_user_pools_web_client_id:
    process.env.REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID,
  secure: true,
  oauth: {
    domain: process.env.REACT_APP_DOMAIN,
    scope: [
      'phone',
      'email',
      'profile',
      'openid',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: process.env.REACT_APP_REDIRECT_URL,
    redirectSignOut: process.env.REACT_APP_REDIRECT_URL,
    responseType: 'token',
  },

  aws_cognito_social_providers: ['GOOGLE'],
};

Auth.configure(awsConfig);

export const config = {
  REGION: process.env.REACT_APP_AWS_PROJECT_REGION,
  USER_POOL_ID: process.env.REACT_APP_AWS_USER_POOLS_ID,
  USER_POOL_APP_CLIENT_ID: process.env.REACT_APP_AWS_USER_POOLS_APP_CLIENT_ID,
};

export default awsConfig;
